"""Generate bb_epaper 1-bit sprites from vendored Lucide SVGs."""
import argparse
from io import BytesIO
from pathlib import Path
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw
import resvg_py

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/weather/lucide"
OUTPUT = ROOT / "include/assets/weather/weather_bitmaps.h"
# Order matches calendar::WeatherIcon; unknown IDs select Cloudy.
ICONS = ("sun", "cloud", "cloud-sun", "cloud-rain", "cloud-snow", "cloud-fog",
         "moon", "cloud-moon", "cloud-drizzle", "cloud-rain-wind", "cloud-lightning", "wind")
SIZES = (32, 48)

def rasterize(name, size):
    svg = ET.fromstring((SOURCE / f"{name}.svg").read_text(encoding="utf-8"))
    svg.set("stroke", "#000000")
    png = resvg_py.svg_to_bytes(svg_string=ET.tostring(svg, encoding="unicode"),
        width=size * 4, height=size * 4, background="#ffffff", skip_system_fonts=True)
    image = Image.open(BytesIO(png)).convert("L").resize((size, size), Image.Resampling.LANCZOS)
    return image.point(lambda value: 255 if value >= 160 else 0, mode="1")

def pack(image):
    size = image.width
    data = bytearray(((size + 7) // 8) * size)
    for y in range(size):
        for x in range(size):
            if image.getpixel((x, y)) == 0:
                data[y * ((size + 7) // 8) + x // 8] |= 0x80 >> (x % 8)
    return data

def generate(preview=None):
    lines = ["// Generated by tools/generate_weather_icons.py; do not edit.",
        "// Lucide ISC / Feather MIT notices: assets/weather/lucide/LICENSE.",
        "// Row-major, MSB first, 1 = foreground, 0 = transparent.",
        "#pragma once", "#include <calendar/weather_icons.h>", "#ifndef PROGMEM",
        "#define PROGMEM", "#endif", "namespace calendar {", "namespace WeatherIcons {", "namespace {"]
    sheet = Image.new("RGB", (len(ICONS) * 76, 164), "white")
    labels = ImageDraw.Draw(sheet)
    for row, size in enumerate(SIZES):
        for column, name in enumerate(ICONS):
            image = rasterize(name, size)
            data = pack(image)
            assert len(data) == ((size + 7) // 8) * size and any(data)
            symbol = f"k_{name.replace('-', '_')}_{size}"
            lines.append(f"const uint8_t {symbol}[] PROGMEM = {{")
            for offset in range(0, len(data), 16):
                lines.append("  " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
            lines.append("};")
            sheet.paste(image.convert("RGB"), (column * 76 + (76 - size) // 2, row * 82 + 3))
            labels.text((column * 76 + 2, row * 82 + 54), name.replace("cloud-", "c-"), fill="black")
        lines.append(f"const WeatherBitmap kWeather{size}[] = {{")
        for name in ICONS:
            lines.append(f"  {{k_{name.replace('-', '_')}_{size}, {size}, {size}}},")
        lines.append("};")
    lines += ["} // namespace", "} // namespace WeatherIcons", "} // namespace calendar", ""]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    if preview:
        preview.parent.mkdir(parents=True, exist_ok=True)
        sheet.save(preview)
    print(f"Generated {len(ICONS)} icons at {SIZES}: 4,992 bitmap bytes.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", type=Path, help="Optional development contact-sheet PNG")
    generate(parser.parse_args().preview)
