"""Generate 16px footer sprites using the weather icon rasterizer/dependencies."""
from pathlib import Path
import sys
sys.dont_write_bytecode = True
import generate_weather_icons as rasterizer

ROOT = Path(__file__).resolve().parents[1]
rasterizer.SOURCE = ROOT / "assets/status/lucide"
ICONS = ("battery", "calendar", "wifi", "wifi-off")

lines = ["// Generated by tools/generate_status_icons.py; do not edit.",
         "// Lucide ISC / Feather MIT notices: assets/status/lucide/LICENSE.",
         "// Row-major, MSB first, 1 = foreground, 0 = transparent.",
         "#pragma once", "#include <stdint.h>",
         "#ifndef PROGMEM", "#define PROGMEM", "#endif",
         "namespace calendar { namespace StatusIcons {"]
for name in ICONS:
    data = rasterizer.pack(rasterizer.rasterize(name, 16))
    assert len(data) == 32 and any(data)
    lines.append(f"const uint8_t k_{name.replace('-', '_')}[] PROGMEM = {{")
    for offset in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
    lines.append("};")
lines += ["} } // namespace calendar::StatusIcons", ""]
output = ROOT / "include/assets/status/status_bitmaps.h"
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print("Generated four 16px footer icons (128 bitmap bytes).")
